### ISSUE TITLE
Protokol doesn't like hyphens in project names

### ISSUE THREAD

**Issue by pporada-gl** [metalseargolid/protokoll#4]
```
$ protokoll project create jenkins-build-glapp
Traceback (most recent call last):
  File "/usr/local/bin/protokoll", line 9, in <module>
    load_entry_point('protokoll==0.1.3', 'console_scripts', 'protokoll')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/__main__.py", line 44, in create
    dbo.create_project(project_name, close=True)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 59, in create_project
    "is_running INT NOT NULL)", close, False, tn=project_name)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 242, in __execute
    cursor.execute(query)
sqlite3.OperationalError: near "-": syntax error
```

I then put quotes around the project name.
```
$ protokoll project create "jenkins-build-glapp"
Traceback (most recent call last):
  File "/usr/local/bin/protokoll", line 9, in <module>
    load_entry_point('protokoll==0.1.3', 'console_scripts', 'protokoll')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/__main__.py", line 44, in create
    dbo.create_project(project_name, close=True)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 59, in create_project
    "is_running INT NOT NULL)", close, False, tn=project_name)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 242, in __execute
    cursor.execute(query)
sqlite3.OperationalError: near "-": syntax error
```

I then tried to escape the hyphens but got blown up again. Escaping the escapes also causes protokoll to explode.
```
$ protokoll project create "jenkins\-build\-glapp"
Traceback (most recent call last):
  File "/usr/local/bin/protokoll", line 9, in <module>
    load_entry_point('protokoll==0.1.3', 'console_scripts', 'protokoll')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/__main__.py", line 44, in create
    dbo.create_project(project_name, close=True)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 59, in create_project
    "is_running INT NOT NULL)", close, False, tn=project_name)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 242, in __execute
    cursor.execute(query)
sqlite3.OperationalError: unrecognized token: "\"
```

**Comment by metalseargolid** [comment]
@pporada-gl: This was fixed when I reworked the database to use a more standard approach.
