### ISSUE TITLE
Using a non-existant project name causes a crash

### ISSUE THREAD

**Issue by metalseargolid** [metalseargolid/protokoll#7]
p task list notaproj
```
Traceback (most recent call last):
  File "/usr/local/bin/p", line 9, in <module>
    load_entry_point('protokoll==0.1.3', 'console_scripts', 'p')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 680, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1027, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/__main__.py", line 124, in list
    tasks = dbo.get_project_tasks(project_name, days, close=True)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 158, in get_project_tasks
    tn=project_name, d=days)
  File "/usr/local/lib/python2.7/dist-packages/protokoll/db.py", line 242, in __execute
    cursor.execute(query)
sqlite3.OperationalError: no such table: notaproj
```

**Comment by metalseargolid** [comment]
This has been fixed
